# Example configuration file that
# - updates dependencies daily

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Das Limit muss > 0 sein, damit Dependabot Pull Requests erstellen kann.
    # Der Standardwert ist 5.
    open-pull-requests-limit: 5
